// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ods.proto

/*
Package trud is a generated protocol buffer package.

It is generated from these files:
	ods.proto

It has these top-level messages:
	NHSPD
	ODSOrganisation
	SearchPostcode
	SearchOrganisation
*/
package trud

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Postcode user type
type NHSPD_UserType int32

const (
	NHSPD_SMALL NHSPD_UserType = 0
	NHSPD_LARGE NHSPD_UserType = 1
)

var NHSPD_UserType_name = map[int32]string{
	0: "SMALL",
	1: "LARGE",
}
var NHSPD_UserType_value = map[string]int32{
	"SMALL": 0,
	"LARGE": 1,
}

func (x NHSPD_UserType) String() string {
	return proto.EnumName(NHSPD_UserType_name, int32(x))
}
func (NHSPD_UserType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Grid reference positional quality indicator
type NHSPD_GridReferenceQuality int32

const (
	NHSPD_UNKNOWN_GRID_REF_QUALITY NHSPD_GridReferenceQuality = 0
	NHSPD_WITHIN_BUILDING          NHSPD_GridReferenceQuality = 1
	NHSPD_WITHIN_BUILDING_FROM_MAP NHSPD_GridReferenceQuality = 2
	NHSPD_WITHIN_50_METRES         NHSPD_GridReferenceQuality = 3
	NHSPD_POSTCODE_UNIT_MEAN       NHSPD_GridReferenceQuality = 4
	NHSPD_IMPUTED_BY_ONS           NHSPD_GridReferenceQuality = 5
	NHSPD_POSTCODE_SECTOR_MEAN     NHSPD_GridReferenceQuality = 6
	NHSPD_TERMINATED_LAST_KNOWN    NHSPD_GridReferenceQuality = 8
	NHSPD_NO_GRID_REFERENCE        NHSPD_GridReferenceQuality = 9
)

var NHSPD_GridReferenceQuality_name = map[int32]string{
	0: "UNKNOWN_GRID_REF_QUALITY",
	1: "WITHIN_BUILDING",
	2: "WITHIN_BUILDING_FROM_MAP",
	3: "WITHIN_50_METRES",
	4: "POSTCODE_UNIT_MEAN",
	5: "IMPUTED_BY_ONS",
	6: "POSTCODE_SECTOR_MEAN",
	8: "TERMINATED_LAST_KNOWN",
	9: "NO_GRID_REFERENCE",
}
var NHSPD_GridReferenceQuality_value = map[string]int32{
	"UNKNOWN_GRID_REF_QUALITY": 0,
	"WITHIN_BUILDING":          1,
	"WITHIN_BUILDING_FROM_MAP": 2,
	"WITHIN_50_METRES":         3,
	"POSTCODE_UNIT_MEAN":       4,
	"IMPUTED_BY_ONS":           5,
	"POSTCODE_SECTOR_MEAN":     6,
	"TERMINATED_LAST_KNOWN":    8,
	"NO_GRID_REFERENCE":        9,
}

func (x NHSPD_GridReferenceQuality) String() string {
	return proto.EnumName(NHSPD_GridReferenceQuality_name, int32(x))
}
func (NHSPD_GridReferenceQuality) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1}
}

// Census enumeration district positional quality indicator
type NHSPD_CensusCodeQuality int32

const (
	NHSPD_UNKNOWN_CENSUS_QUALITY            NHSPD_CensusCodeQuality = 0
	NHSPD_POINT_IN_POLYGON                  NHSPD_CensusCodeQuality = 1
	NHSPD_NORTHERN_IRELAND                  NHSPD_CensusCodeQuality = 6
	NHSPD_SCOTLAND_CHANNELISLANDS_ISLEOFMAN NHSPD_CensusCodeQuality = 9
)

var NHSPD_CensusCodeQuality_name = map[int32]string{
	0: "UNKNOWN_CENSUS_QUALITY",
	1: "POINT_IN_POLYGON",
	6: "NORTHERN_IRELAND",
	9: "SCOTLAND_CHANNELISLANDS_ISLEOFMAN",
}
var NHSPD_CensusCodeQuality_value = map[string]int32{
	"UNKNOWN_CENSUS_QUALITY":            0,
	"POINT_IN_POLYGON":                  1,
	"NORTHERN_IRELAND":                  6,
	"SCOTLAND_CHANNELISLANDS_ISLEOFMAN": 9,
}

func (x NHSPD_CensusCodeQuality) String() string {
	return proto.EnumName(NHSPD_CensusCodeQuality_name, int32(x))
}
func (NHSPD_CensusCodeQuality) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

// NHSPD is the NHS postcode directory
// See https://isd.digital.nhs.uk/trud3/user/authenticated/group/0/pack/5/subpack/242/releases
//
type NHSPD struct {
	Postcode                 string                     `protobuf:"bytes,1,opt,name=postcode" json:"postcode,omitempty"`
	PostcodeEgif             string                     `protobuf:"bytes,2,opt,name=postcode_egif,json=postcodeEgif" json:"postcode_egif,omitempty"`
	DateIntroduction         string                     `protobuf:"bytes,3,opt,name=date_introduction,json=dateIntroduction" json:"date_introduction,omitempty"`
	DateTermination          string                     `protobuf:"bytes,4,opt,name=date_termination,json=dateTermination" json:"date_termination,omitempty"`
	OsEasting_100M           string                     `protobuf:"bytes,5,opt,name=os_easting_100m,json=osEasting100m" json:"os_easting_100m,omitempty"`
	OsNorthing_100M          string                     `protobuf:"bytes,6,opt,name=os_northing_100m,json=osNorthing100m" json:"os_northing_100m,omitempty"`
	County                   string                     `protobuf:"bytes,7,opt,name=county" json:"county,omitempty"`
	LocalAuthorityOrg        string                     `protobuf:"bytes,8,opt,name=local_authority_org,json=localAuthorityOrg" json:"local_authority_org,omitempty"`
	LocalAuthorityDistrict   string                     `protobuf:"bytes,9,opt,name=local_authority_district,json=localAuthorityDistrict" json:"local_authority_district,omitempty"`
	ElectoralWard            string                     `protobuf:"bytes,10,opt,name=electoral_ward,json=electoralWard" json:"electoral_ward,omitempty"`
	UserType                 NHSPD_UserType             `protobuf:"varint,11,opt,name=user_type,json=userType,enum=trud.NHSPD_UserType" json:"user_type,omitempty"`
	GridReferenceQuality     NHSPD_GridReferenceQuality `protobuf:"varint,12,opt,name=grid_reference_quality,json=gridReferenceQuality,enum=trud.NHSPD_GridReferenceQuality" json:"grid_reference_quality,omitempty"`
	Country                  string                     `protobuf:"bytes,13,opt,name=country" json:"country,omitempty"`
	HealthAuthorityPre_2013  string                     `protobuf:"bytes,14,opt,name=health_authority_pre_2013,json=healthAuthorityPre2013" json:"health_authority_pre_2013,omitempty"`
	Region                   string                     `protobuf:"bytes,15,opt,name=region" json:"region,omitempty"`
	HealthAuthorityPre_2002  string                     `protobuf:"bytes,16,opt,name=health_authority_pre_2002,json=healthAuthorityPre2002" json:"health_authority_pre_2002,omitempty"`
	NhsEnglandRegion         string                     `protobuf:"bytes,17,opt,name=nhs_england_region,json=nhsEnglandRegion" json:"nhs_england_region,omitempty"`
	CcgLhbChpLcgPhd          string                     `protobuf:"bytes,18,opt,name=ccg_lhb_chp_lcg_phd,json=ccgLhbChpLcgPhd" json:"ccg_lhb_chp_lcg_phd,omitempty"`
	Census_1991Ogss          string                     `protobuf:"bytes,19,opt,name=census_1991_ogss,json=census1991Ogss" json:"census_1991_ogss,omitempty"`
	Census_1991Code          string                     `protobuf:"bytes,20,opt,name=census_1991_code,json=census1991Code" json:"census_1991_code,omitempty"`
	CensusCodeQuality        NHSPD_CensusCodeQuality    `protobuf:"varint,21,opt,name=census_code_quality,json=censusCodeQuality,enum=trud.NHSPD_CensusCodeQuality" json:"census_code_quality,omitempty"`
	Ward_1998                string                     `protobuf:"bytes,22,opt,name=ward_1998,json=ward1998" json:"ward_1998,omitempty"`
	Census_2001Area          string                     `protobuf:"bytes,23,opt,name=census_2001_area,json=census2001Area" json:"census_2001_area,omitempty"`
	NhsEnglandRlo            string                     `protobuf:"bytes,24,opt,name=nhs_england_rlo,json=nhsEnglandRlo" json:"nhs_england_rlo,omitempty"`
	FormerPanSha             string                     `protobuf:"bytes,25,opt,name=former_pan_sha,json=formerPanSha" json:"former_pan_sha,omitempty"`
	Census_2001Lsoa          string                     `protobuf:"bytes,26,opt,name=census_2001_lsoa,json=census2001Lsoa" json:"census_2001_lsoa,omitempty"`
	Census_2001Rural         string                     `protobuf:"bytes,27,opt,name=census_2001_rural,json=census2001Rural" json:"census_2001_rural,omitempty"`
	Census_2001Msoa          string                     `protobuf:"bytes,28,opt,name=census_2001_msoa,json=census2001Msoa" json:"census_2001_msoa,omitempty"`
	FormerCancerNetwork      string                     `protobuf:"bytes,29,opt,name=former_cancer_network,json=formerCancerNetwork" json:"former_cancer_network,omitempty"`
	StrategicClinicalNetwork string                     `protobuf:"bytes,30,opt,name=strategic_clinical_network,json=strategicClinicalNetwork" json:"strategic_clinical_network,omitempty"`
	HealthAuthorityPre_2006  string                     `protobuf:"bytes,31,opt,name=health_authority_pre_2006,json=healthAuthorityPre2006" json:"health_authority_pre_2006,omitempty"`
	PctPre_2006              string                     `protobuf:"bytes,32,opt,name=pct_pre_2006,json=pctPre2006" json:"pct_pre_2006,omitempty"`
	ItClusterPre_2007        string                     `protobuf:"bytes,33,opt,name=it_cluster_pre_2007,json=itClusterPre2007" json:"it_cluster_pre_2007,omitempty"`
	WestminsterConsituency   string                     `protobuf:"bytes,34,opt,name=westminster_consituency,json=westminsterConsituency" json:"westminster_consituency,omitempty"`
	CancerRegistry           string                     `protobuf:"bytes,35,opt,name=cancer_registry,json=cancerRegistry" json:"cancer_registry,omitempty"`
	Pct                      string                     `protobuf:"bytes,36,opt,name=pct" json:"pct,omitempty"`
	OsEasting_1M             string                     `protobuf:"bytes,37,opt,name=os_easting_1m,json=osEasting1m" json:"os_easting_1m,omitempty"`
	OsNorthing_1M            string                     `protobuf:"bytes,38,opt,name=os_northing_1m,json=osNorthing1m" json:"os_northing_1m,omitempty"`
	Census_2011Area          string                     `protobuf:"bytes,39,opt,name=census_2011_area,json=census2011Area" json:"census_2011_area,omitempty"`
	Census_2011Lsoa          string                     `protobuf:"bytes,40,opt,name=census_2011_lsoa,json=census2011Lsoa" json:"census_2011_lsoa,omitempty"`
	Census_2011Msoa          string                     `protobuf:"bytes,41,opt,name=census_2011_msoa,json=census2011Msoa" json:"census_2011_msoa,omitempty"`
}

func (m *NHSPD) Reset()                    { *m = NHSPD{} }
func (m *NHSPD) String() string            { return proto.CompactTextString(m) }
func (*NHSPD) ProtoMessage()               {}
func (*NHSPD) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NHSPD) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *NHSPD) GetPostcodeEgif() string {
	if m != nil {
		return m.PostcodeEgif
	}
	return ""
}

func (m *NHSPD) GetDateIntroduction() string {
	if m != nil {
		return m.DateIntroduction
	}
	return ""
}

func (m *NHSPD) GetDateTermination() string {
	if m != nil {
		return m.DateTermination
	}
	return ""
}

func (m *NHSPD) GetOsEasting_100M() string {
	if m != nil {
		return m.OsEasting_100M
	}
	return ""
}

func (m *NHSPD) GetOsNorthing_100M() string {
	if m != nil {
		return m.OsNorthing_100M
	}
	return ""
}

func (m *NHSPD) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *NHSPD) GetLocalAuthorityOrg() string {
	if m != nil {
		return m.LocalAuthorityOrg
	}
	return ""
}

func (m *NHSPD) GetLocalAuthorityDistrict() string {
	if m != nil {
		return m.LocalAuthorityDistrict
	}
	return ""
}

func (m *NHSPD) GetElectoralWard() string {
	if m != nil {
		return m.ElectoralWard
	}
	return ""
}

func (m *NHSPD) GetUserType() NHSPD_UserType {
	if m != nil {
		return m.UserType
	}
	return NHSPD_SMALL
}

func (m *NHSPD) GetGridReferenceQuality() NHSPD_GridReferenceQuality {
	if m != nil {
		return m.GridReferenceQuality
	}
	return NHSPD_UNKNOWN_GRID_REF_QUALITY
}

func (m *NHSPD) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *NHSPD) GetHealthAuthorityPre_2013() string {
	if m != nil {
		return m.HealthAuthorityPre_2013
	}
	return ""
}

func (m *NHSPD) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *NHSPD) GetHealthAuthorityPre_2002() string {
	if m != nil {
		return m.HealthAuthorityPre_2002
	}
	return ""
}

func (m *NHSPD) GetNhsEnglandRegion() string {
	if m != nil {
		return m.NhsEnglandRegion
	}
	return ""
}

func (m *NHSPD) GetCcgLhbChpLcgPhd() string {
	if m != nil {
		return m.CcgLhbChpLcgPhd
	}
	return ""
}

func (m *NHSPD) GetCensus_1991Ogss() string {
	if m != nil {
		return m.Census_1991Ogss
	}
	return ""
}

func (m *NHSPD) GetCensus_1991Code() string {
	if m != nil {
		return m.Census_1991Code
	}
	return ""
}

func (m *NHSPD) GetCensusCodeQuality() NHSPD_CensusCodeQuality {
	if m != nil {
		return m.CensusCodeQuality
	}
	return NHSPD_UNKNOWN_CENSUS_QUALITY
}

func (m *NHSPD) GetWard_1998() string {
	if m != nil {
		return m.Ward_1998
	}
	return ""
}

func (m *NHSPD) GetCensus_2001Area() string {
	if m != nil {
		return m.Census_2001Area
	}
	return ""
}

func (m *NHSPD) GetNhsEnglandRlo() string {
	if m != nil {
		return m.NhsEnglandRlo
	}
	return ""
}

func (m *NHSPD) GetFormerPanSha() string {
	if m != nil {
		return m.FormerPanSha
	}
	return ""
}

func (m *NHSPD) GetCensus_2001Lsoa() string {
	if m != nil {
		return m.Census_2001Lsoa
	}
	return ""
}

func (m *NHSPD) GetCensus_2001Rural() string {
	if m != nil {
		return m.Census_2001Rural
	}
	return ""
}

func (m *NHSPD) GetCensus_2001Msoa() string {
	if m != nil {
		return m.Census_2001Msoa
	}
	return ""
}

func (m *NHSPD) GetFormerCancerNetwork() string {
	if m != nil {
		return m.FormerCancerNetwork
	}
	return ""
}

func (m *NHSPD) GetStrategicClinicalNetwork() string {
	if m != nil {
		return m.StrategicClinicalNetwork
	}
	return ""
}

func (m *NHSPD) GetHealthAuthorityPre_2006() string {
	if m != nil {
		return m.HealthAuthorityPre_2006
	}
	return ""
}

func (m *NHSPD) GetPctPre_2006() string {
	if m != nil {
		return m.PctPre_2006
	}
	return ""
}

func (m *NHSPD) GetItClusterPre_2007() string {
	if m != nil {
		return m.ItClusterPre_2007
	}
	return ""
}

func (m *NHSPD) GetWestminsterConsituency() string {
	if m != nil {
		return m.WestminsterConsituency
	}
	return ""
}

func (m *NHSPD) GetCancerRegistry() string {
	if m != nil {
		return m.CancerRegistry
	}
	return ""
}

func (m *NHSPD) GetPct() string {
	if m != nil {
		return m.Pct
	}
	return ""
}

func (m *NHSPD) GetOsEasting_1M() string {
	if m != nil {
		return m.OsEasting_1M
	}
	return ""
}

func (m *NHSPD) GetOsNorthing_1M() string {
	if m != nil {
		return m.OsNorthing_1M
	}
	return ""
}

func (m *NHSPD) GetCensus_2011Area() string {
	if m != nil {
		return m.Census_2011Area
	}
	return ""
}

func (m *NHSPD) GetCensus_2011Lsoa() string {
	if m != nil {
		return m.Census_2011Lsoa
	}
	return ""
}

func (m *NHSPD) GetCensus_2011Msoa() string {
	if m != nil {
		return m.Census_2011Msoa
	}
	return ""
}

type ODSOrganisation struct {
	OrganisationCode         string `protobuf:"bytes,1,opt,name=organisation_code,json=organisationCode" json:"organisation_code,omitempty"`
	Name                     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NationalGrouping         string `protobuf:"bytes,3,opt,name=national_grouping,json=nationalGrouping" json:"national_grouping,omitempty"`
	HighLevelHealthGeography string `protobuf:"bytes,4,opt,name=high_level_health_geography,json=highLevelHealthGeography" json:"high_level_health_geography,omitempty"`
	Address1                 string `protobuf:"bytes,5,opt,name=address1" json:"address1,omitempty"`
	Address2                 string `protobuf:"bytes,6,opt,name=address2" json:"address2,omitempty"`
	Address3                 string `protobuf:"bytes,7,opt,name=address3" json:"address3,omitempty"`
	Address4                 string `protobuf:"bytes,8,opt,name=address4" json:"address4,omitempty"`
	Address5                 string `protobuf:"bytes,9,opt,name=address5" json:"address5,omitempty"`
	Postcode                 string `protobuf:"bytes,10,opt,name=postcode" json:"postcode,omitempty"`
	OpenDate                 string `protobuf:"bytes,11,opt,name=open_date,json=openDate" json:"open_date,omitempty"`
	CloseDate                string `protobuf:"bytes,12,opt,name=close_date,json=closeDate" json:"close_date,omitempty"`
	TelephoneNumber          string `protobuf:"bytes,18,opt,name=telephone_number,json=telephoneNumber" json:"telephone_number,omitempty"`
	AmendedRecordIndicator   bool   `protobuf:"varint,22,opt,name=amended_record_indicator,json=amendedRecordIndicator" json:"amended_record_indicator,omitempty"`
}

func (m *ODSOrganisation) Reset()                    { *m = ODSOrganisation{} }
func (m *ODSOrganisation) String() string            { return proto.CompactTextString(m) }
func (*ODSOrganisation) ProtoMessage()               {}
func (*ODSOrganisation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ODSOrganisation) GetOrganisationCode() string {
	if m != nil {
		return m.OrganisationCode
	}
	return ""
}

func (m *ODSOrganisation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ODSOrganisation) GetNationalGrouping() string {
	if m != nil {
		return m.NationalGrouping
	}
	return ""
}

func (m *ODSOrganisation) GetHighLevelHealthGeography() string {
	if m != nil {
		return m.HighLevelHealthGeography
	}
	return ""
}

func (m *ODSOrganisation) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *ODSOrganisation) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *ODSOrganisation) GetAddress3() string {
	if m != nil {
		return m.Address3
	}
	return ""
}

func (m *ODSOrganisation) GetAddress4() string {
	if m != nil {
		return m.Address4
	}
	return ""
}

func (m *ODSOrganisation) GetAddress5() string {
	if m != nil {
		return m.Address5
	}
	return ""
}

func (m *ODSOrganisation) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *ODSOrganisation) GetOpenDate() string {
	if m != nil {
		return m.OpenDate
	}
	return ""
}

func (m *ODSOrganisation) GetCloseDate() string {
	if m != nil {
		return m.CloseDate
	}
	return ""
}

func (m *ODSOrganisation) GetTelephoneNumber() string {
	if m != nil {
		return m.TelephoneNumber
	}
	return ""
}

func (m *ODSOrganisation) GetAmendedRecordIndicator() bool {
	if m != nil {
		return m.AmendedRecordIndicator
	}
	return false
}

type SearchPostcode struct {
	Postcode string `protobuf:"bytes,1,opt,name=postcode" json:"postcode,omitempty"`
}

func (m *SearchPostcode) Reset()                    { *m = SearchPostcode{} }
func (m *SearchPostcode) String() string            { return proto.CompactTextString(m) }
func (*SearchPostcode) ProtoMessage()               {}
func (*SearchPostcode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchPostcode) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

type SearchOrganisation struct {
	OrganisationCode string `protobuf:"bytes,1,opt,name=organisation_code,json=organisationCode" json:"organisation_code,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *SearchOrganisation) Reset()                    { *m = SearchOrganisation{} }
func (m *SearchOrganisation) String() string            { return proto.CompactTextString(m) }
func (*SearchOrganisation) ProtoMessage()               {}
func (*SearchOrganisation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SearchOrganisation) GetOrganisationCode() string {
	if m != nil {
		return m.OrganisationCode
	}
	return ""
}

func (m *SearchOrganisation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*NHSPD)(nil), "trud.NHSPD")
	proto.RegisterType((*ODSOrganisation)(nil), "trud.ODSOrganisation")
	proto.RegisterType((*SearchPostcode)(nil), "trud.SearchPostcode")
	proto.RegisterType((*SearchOrganisation)(nil), "trud.SearchOrganisation")
	proto.RegisterEnum("trud.NHSPD_UserType", NHSPD_UserType_name, NHSPD_UserType_value)
	proto.RegisterEnum("trud.NHSPD_GridReferenceQuality", NHSPD_GridReferenceQuality_name, NHSPD_GridReferenceQuality_value)
	proto.RegisterEnum("trud.NHSPD_CensusCodeQuality", NHSPD_CensusCodeQuality_name, NHSPD_CensusCodeQuality_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Trud service

type TrudClient interface {
	GetPostcode(ctx context.Context, in *SearchPostcode, opts ...grpc.CallOption) (*NHSPD, error)
	GetOrganisation(ctx context.Context, in *SearchOrganisation, opts ...grpc.CallOption) (*ODSOrganisation, error)
}

type trudClient struct {
	cc *grpc.ClientConn
}

func NewTrudClient(cc *grpc.ClientConn) TrudClient {
	return &trudClient{cc}
}

func (c *trudClient) GetPostcode(ctx context.Context, in *SearchPostcode, opts ...grpc.CallOption) (*NHSPD, error) {
	out := new(NHSPD)
	err := grpc.Invoke(ctx, "/trud.Trud/GetPostcode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trudClient) GetOrganisation(ctx context.Context, in *SearchOrganisation, opts ...grpc.CallOption) (*ODSOrganisation, error) {
	out := new(ODSOrganisation)
	err := grpc.Invoke(ctx, "/trud.Trud/GetOrganisation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Trud service

type TrudServer interface {
	GetPostcode(context.Context, *SearchPostcode) (*NHSPD, error)
	GetOrganisation(context.Context, *SearchOrganisation) (*ODSOrganisation, error)
}

func RegisterTrudServer(s *grpc.Server, srv TrudServer) {
	s.RegisterService(&_Trud_serviceDesc, srv)
}

func _Trud_GetPostcode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPostcode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrudServer).GetPostcode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trud.Trud/GetPostcode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrudServer).GetPostcode(ctx, req.(*SearchPostcode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trud_GetOrganisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrganisation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrudServer).GetOrganisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trud.Trud/GetOrganisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrudServer).GetOrganisation(ctx, req.(*SearchOrganisation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Trud_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trud.Trud",
	HandlerType: (*TrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostcode",
			Handler:    _Trud_GetPostcode_Handler,
		},
		{
			MethodName: "GetOrganisation",
			Handler:    _Trud_GetOrganisation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ods.proto",
}

func init() { proto.RegisterFile("ods.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xd1, 0x72, 0xdb, 0xb8,
	0x15, 0x5d, 0x6d, 0x14, 0xaf, 0x84, 0xc4, 0x36, 0x05, 0xd9, 0x0a, 0xe2, 0x24, 0xad, 0x57, 0xbb,
	0xd9, 0x75, 0xba, 0xa9, 0x47, 0x52, 0xba, 0x9b, 0xcd, 0x4c, 0xfb, 0xa0, 0x48, 0x8c, 0xcc, 0x54,
	0x22, 0xb5, 0xa4, 0xd4, 0x4c, 0x9e, 0x30, 0x30, 0x09, 0x93, 0x9c, 0x52, 0x04, 0x0b, 0x42, 0xcd,
	0x68, 0xa6, 0x4f, 0xfd, 0x8b, 0x7e, 0x4b, 0xbf, 0xab, 0xef, 0x1d, 0x00, 0xa4, 0x4c, 0xa9, 0xa9,
	0x9f, 0xf6, 0x8d, 0xf7, 0x9c, 0x73, 0x41, 0x10, 0xf7, 0x5e, 0xf0, 0x80, 0x26, 0x0b, 0xf2, 0xcb,
	0x8c, 0x33, 0xc1, 0x60, 0x5d, 0xf0, 0x75, 0xd0, 0xfd, 0x77, 0x0b, 0xdc, 0xb7, 0xaf, 0xbc, 0xf9,
	0x18, 0x9e, 0x81, 0x46, 0xc6, 0x72, 0xe1, 0xb3, 0x80, 0xa2, 0xda, 0x79, 0xed, 0xa2, 0xe9, 0x6e,
	0x63, 0xf8, 0x0d, 0x38, 0x2c, 0x9f, 0x31, 0x0d, 0xe3, 0x1b, 0xf4, 0xa5, 0x12, 0x3c, 0x2c, 0x41,
	0x33, 0x8c, 0x6f, 0xe0, 0x0f, 0xa0, 0x15, 0x10, 0x41, 0x71, 0x9c, 0x0a, 0xce, 0x82, 0xb5, 0x2f,
	0x62, 0x96, 0xa2, 0x7b, 0x4a, 0x68, 0x48, 0xc2, 0xaa, 0xe0, 0xf0, 0x05, 0x50, 0x18, 0x16, 0x94,
	0xaf, 0xe2, 0x94, 0x28, 0x6d, 0x5d, 0x69, 0x8f, 0x25, 0xbe, 0xb8, 0x85, 0xe1, 0x77, 0xe0, 0x98,
	0xe5, 0x98, 0x92, 0x5c, 0xc4, 0x69, 0x88, 0xfb, 0xbd, 0xde, 0x0a, 0xdd, 0x57, 0xca, 0x43, 0x96,
	0x9b, 0x1a, 0x95, 0x20, 0xbc, 0x00, 0x06, 0xcb, 0x71, 0xca, 0xb8, 0x88, 0xb6, 0xc2, 0x03, 0x25,
	0x3c, 0x62, 0xb9, 0x5d, 0xc0, 0x4a, 0xd9, 0x01, 0x07, 0x3e, 0x5b, 0xa7, 0x62, 0x83, 0xbe, 0x52,
	0x7c, 0x11, 0xc1, 0x4b, 0xd0, 0x4e, 0x98, 0x4f, 0x12, 0x4c, 0xd6, 0x22, 0x62, 0x3c, 0x16, 0x1b,
	0xcc, 0x78, 0x88, 0x1a, 0x4a, 0xd4, 0x52, 0xd4, 0xb0, 0x64, 0x1c, 0x1e, 0xc2, 0x9f, 0x01, 0xda,
	0xd7, 0x07, 0x71, 0x2e, 0x78, 0xec, 0x0b, 0xd4, 0x54, 0x49, 0x9d, 0xdd, 0xa4, 0x71, 0xc1, 0xc2,
	0xe7, 0xe0, 0x88, 0x26, 0xd4, 0x17, 0x8c, 0x93, 0x04, 0x7f, 0x22, 0x3c, 0x40, 0x40, 0x7f, 0xd2,
	0x16, 0xfd, 0x40, 0x78, 0x00, 0xfb, 0xa0, 0xb9, 0xce, 0x29, 0xc7, 0x62, 0x93, 0x51, 0xf4, 0xe0,
	0xbc, 0x76, 0x71, 0x34, 0x38, 0xb9, 0x94, 0x75, 0xbb, 0x54, 0x35, 0xbb, 0x5c, 0xe6, 0x94, 0x2f,
	0x36, 0x19, 0x75, 0x1b, 0xeb, 0xe2, 0x09, 0xfe, 0x05, 0x74, 0x42, 0x1e, 0x07, 0x98, 0xd3, 0x1b,
	0xca, 0x69, 0xea, 0x53, 0xfc, 0xb7, 0x35, 0x49, 0x62, 0xb1, 0x41, 0x0f, 0x55, 0xfe, 0x79, 0x35,
	0x7f, 0xc2, 0xe3, 0xc0, 0x2d, 0x85, 0xbf, 0x68, 0x9d, 0x7b, 0x12, 0x7e, 0x06, 0x85, 0x08, 0x7c,
	0xa5, 0x4e, 0x89, 0x6f, 0xd0, 0xa1, 0xda, 0x6a, 0x19, 0xc2, 0x37, 0xe0, 0x71, 0x44, 0x49, 0x22,
	0xa2, 0xca, 0x31, 0x64, 0x9c, 0xe2, 0x41, 0xaf, 0xff, 0x0a, 0x1d, 0xe9, 0x63, 0xd0, 0x82, 0xed,
	0x39, 0xcc, 0x39, 0x95, 0xac, 0x2c, 0x04, 0xa7, 0xa1, 0xac, 0xfd, 0xb1, 0x2e, 0x84, 0x8e, 0xee,
	0x58, 0xb2, 0x37, 0x40, 0xc6, 0xff, 0x5f, 0xb2, 0x37, 0x80, 0x2f, 0x01, 0x4c, 0xa3, 0x1c, 0xd3,
	0x34, 0x4c, 0x48, 0x2a, 0x8f, 0x41, 0x2d, 0xdf, 0xd2, 0x6d, 0x98, 0x46, 0xb9, 0xa9, 0x09, 0x57,
	0xbf, 0xe8, 0x25, 0x68, 0xfb, 0x7e, 0x88, 0x93, 0xe8, 0x1a, 0xfb, 0x51, 0x86, 0x13, 0x3f, 0xc4,
	0x59, 0x14, 0x20, 0xa8, 0x3b, 0xd1, 0xf7, 0xc3, 0x69, 0x74, 0x3d, 0x8a, 0xb2, 0xa9, 0x1f, 0xce,
	0xa3, 0x40, 0x76, 0x98, 0x4f, 0xd3, 0x7c, 0x9d, 0xe3, 0xfe, 0x9b, 0x37, 0x7d, 0xcc, 0xc2, 0x3c,
	0x47, 0x6d, 0xdd, 0x61, 0x1a, 0x97, 0xb0, 0x13, 0xe6, 0xf9, 0xbe, 0x52, 0x0d, 0xd5, 0xc9, 0xbe,
	0x72, 0x24, 0x47, 0x6b, 0x06, 0xda, 0x85, 0x52, 0x4d, 0x57, 0x59, 0xac, 0x53, 0x55, 0xac, 0x67,
	0xd5, 0x62, 0x8d, 0x94, 0x4c, 0x26, 0x95, 0x95, 0x6a, 0xf9, 0xfb, 0x10, 0x7c, 0x02, 0x9a, 0xb2,
	0x9d, 0xe4, 0x6b, 0x7f, 0x46, 0x1d, 0x3d, 0xc6, 0x12, 0x90, 0x71, 0x65, 0x57, 0x83, 0x5e, 0xaf,
	0x8f, 0x09, 0xa7, 0x04, 0x3d, 0xaa, 0xee, 0x4a, 0xc2, 0x43, 0x4e, 0x89, 0x9c, 0xb9, 0x9d, 0x53,
	0x4c, 0x18, 0x42, 0xba, 0x41, 0x2b, 0x47, 0x98, 0x30, 0xf8, 0x2d, 0x38, 0xba, 0x61, 0x7c, 0x45,
	0x39, 0xce, 0x48, 0x8a, 0xf3, 0x88, 0xa0, 0xc7, 0xfa, 0x66, 0xd0, 0xe8, 0x9c, 0xa4, 0x5e, 0x44,
	0xf6, 0xdf, 0x9b, 0xe4, 0x8c, 0xa0, 0xb3, 0xfd, 0xf7, 0x4e, 0x73, 0x46, 0xe0, 0xef, 0x40, 0xab,
	0xaa, 0xe4, 0x6b, 0x4e, 0x12, 0xf4, 0xa4, 0xa8, 0xc6, 0x56, 0xea, 0x4a, 0x78, 0x7f, 0xd5, 0x95,
	0x5c, 0xf5, 0xe9, 0xfe, 0xaa, 0x33, 0xb9, 0xea, 0x00, 0x9c, 0x16, 0xbb, 0xf4, 0x49, 0xea, 0x53,
	0x8e, 0x53, 0x2a, 0x3e, 0x31, 0xfe, 0x57, 0xf4, 0x4c, 0xc9, 0xdb, 0x9a, 0x1c, 0x29, 0xce, 0xd6,
	0x14, 0xfc, 0x23, 0x38, 0xcb, 0x05, 0x27, 0x82, 0x86, 0xb1, 0x8f, 0xfd, 0x24, 0x4e, 0x63, 0x39,
	0xe8, 0x65, 0xe2, 0x6f, 0x54, 0x22, 0xda, 0x2a, 0x46, 0x85, 0xa0, 0xcc, 0xbe, 0xa3, 0x81, 0x7f,
	0x42, 0xbf, 0xbd, 0xa3, 0x81, 0x7f, 0x82, 0xe7, 0xe0, 0x61, 0xe6, 0x8b, 0x5b, 0xf5, 0xb9, 0x52,
	0x83, 0xcc, 0x17, 0xa5, 0xe2, 0xf7, 0xa0, 0x1d, 0x0b, 0xec, 0x27, 0xeb, 0x5c, 0xc8, 0x83, 0xd7,
	0xc2, 0xd7, 0xe8, 0x6b, 0xdd, 0xe3, 0xb1, 0x18, 0x69, 0x46, 0xcb, 0x5f, 0xc3, 0xd7, 0xe0, 0xd1,
	0x27, 0x9a, 0x8b, 0x55, 0x9c, 0x2a, 0xbd, 0xcf, 0xd2, 0x3c, 0x16, 0x6b, 0x9a, 0xfa, 0x1b, 0xd4,
	0xd5, 0x3b, 0xa9, 0xd0, 0xa3, 0x5b, 0x16, 0x7e, 0x0f, 0x8e, 0x8b, 0xf3, 0x92, 0x53, 0x94, 0xcb,
	0xd1, 0xff, 0xa6, 0x38, 0x5f, 0x05, 0xbb, 0x05, 0x0a, 0x0d, 0x70, 0x2f, 0xf3, 0x05, 0xfa, 0x56,
	0x91, 0xf2, 0x11, 0x76, 0xc1, 0x61, 0xf5, 0xce, 0x5e, 0xa1, 0xe7, 0x8a, 0x7b, 0x70, 0x7b, 0x63,
	0xaf, 0x64, 0xef, 0xec, 0xdc, 0xd7, 0x2b, 0xf4, 0x9d, 0xee, 0x9d, 0xca, 0x6d, 0xbd, 0xda, 0xa9,
	0x72, 0xbf, 0xe8, 0xd9, 0xef, 0x77, 0xab, 0xdc, 0xd7, 0x3d, 0xbb, 0xa7, 0x54, 0x5d, 0x76, 0xb1,
	0xaf, 0x54, 0x5d, 0xb6, 0xa7, 0x54, 0x9d, 0xf3, 0x62, 0x5f, 0x29, 0x3b, 0xa7, 0x7b, 0x0e, 0x1a,
	0xe5, 0x1d, 0x0b, 0x9b, 0xe0, 0xbe, 0x37, 0x1b, 0x4e, 0xa7, 0xc6, 0x17, 0xf2, 0x71, 0x3a, 0x74,
	0x27, 0xa6, 0x51, 0xeb, 0xfe, 0xa7, 0x06, 0x4e, 0x3e, 0x77, 0x8d, 0xc2, 0xa7, 0x00, 0x2d, 0xed,
	0x3f, 0xdb, 0xce, 0x07, 0x1b, 0x4f, 0x5c, 0x6b, 0x8c, 0x5d, 0xf3, 0x1d, 0xfe, 0x65, 0x39, 0x9c,
	0x5a, 0x8b, 0x8f, 0xc6, 0x17, 0xb0, 0x0d, 0x8e, 0x3f, 0x58, 0x8b, 0x2b, 0xcb, 0xc6, 0x6f, 0x97,
	0xd6, 0x74, 0x6c, 0xd9, 0x13, 0xa3, 0x26, 0x53, 0xf6, 0x40, 0xfc, 0xce, 0x75, 0x66, 0x78, 0x36,
	0x9c, 0x1b, 0x5f, 0xc2, 0x13, 0x60, 0x14, 0xec, 0x8f, 0x3d, 0x3c, 0x33, 0x17, 0xae, 0xe9, 0x19,
	0xf7, 0x60, 0x07, 0xc0, 0xb9, 0xe3, 0x2d, 0x46, 0xce, 0xd8, 0xc4, 0x4b, 0xdb, 0x5a, 0xe0, 0x99,
	0x39, 0xb4, 0x8d, 0x3a, 0x84, 0xe0, 0xc8, 0x9a, 0xcd, 0x97, 0x0b, 0x73, 0x8c, 0xdf, 0x7e, 0xc4,
	0x8e, 0xed, 0x19, 0xf7, 0x21, 0x02, 0x27, 0x5b, 0xad, 0x67, 0x8e, 0x16, 0x8e, 0xab, 0xd5, 0x07,
	0xf0, 0x31, 0x38, 0x5d, 0x98, 0xee, 0xcc, 0xb2, 0x87, 0x32, 0x61, 0x3a, 0xf4, 0x16, 0x58, 0x6d,
	0xdd, 0x68, 0xc0, 0x53, 0xd0, 0xb2, 0x9d, 0xed, 0x27, 0x98, 0xae, 0x69, 0x8f, 0x4c, 0xa3, 0xd9,
	0xfd, 0x67, 0x0d, 0xb4, 0xfe, 0xe7, 0x46, 0x82, 0x67, 0xa0, 0x53, 0x7e, 0xf4, 0xc8, 0xb4, 0xbd,
	0xa5, 0x57, 0xf9, 0xe4, 0x13, 0x60, 0xcc, 0x1d, 0xcb, 0x5e, 0x60, 0xcb, 0xc6, 0x73, 0x67, 0xfa,
	0x71, 0xe2, 0xd8, 0x46, 0x4d, 0xa2, 0xb6, 0xe3, 0x2e, 0xae, 0x4c, 0xd7, 0xc6, 0x96, 0x6b, 0x4e,
	0x87, 0xf6, 0xd8, 0x38, 0x80, 0xcf, 0xc1, 0xd7, 0xde, 0xc8, 0x59, 0xc8, 0x08, 0x8f, 0xae, 0x86,
	0xb6, 0x6d, 0x4e, 0x2d, 0x4f, 0x46, 0x1e, 0xb6, 0xbc, 0xa9, 0xe9, 0xbc, 0x9b, 0x0d, 0x6d, 0xa3,
	0xd9, 0xfd, 0x57, 0x1d, 0x1c, 0x3b, 0x63, 0xcf, 0xe1, 0x21, 0x49, 0xe3, 0x5c, 0xdb, 0x85, 0x1f,
	0x40, 0x8b, 0x55, 0x62, 0x5c, 0x31, 0x34, 0x46, 0x95, 0x50, 0xb7, 0x2f, 0x04, 0xf5, 0x94, 0xac,
	0x68, 0xe1, 0x67, 0xd4, 0xb3, 0x5c, 0x40, 0x3b, 0x0f, 0x92, 0xe0, 0x90, 0xb3, 0x75, 0x16, 0xa7,
	0x61, 0xe9, 0x63, 0x4a, 0x62, 0x52, 0xe0, 0xf0, 0x4f, 0xe0, 0x49, 0x14, 0x87, 0x11, 0x4e, 0xe8,
	0xdf, 0x69, 0x82, 0x8b, 0x99, 0x0f, 0x29, 0x0b, 0x39, 0xc9, 0xa2, 0x4d, 0x61, 0x69, 0x90, 0x94,
	0x4c, 0xa5, 0xe2, 0x4a, 0x09, 0x26, 0x25, 0x2f, 0x4d, 0x17, 0x09, 0x02, 0x4e, 0xf3, 0xbc, 0x5f,
	0x98, 0x9a, 0x6d, 0x5c, 0xe1, 0x06, 0x85, 0x8f, 0xd9, 0xc6, 0x15, 0xee, 0x55, 0xe1, 0x61, 0xb6,
	0x71, 0x85, 0xfb, 0x43, 0x61, 0x5d, 0xb6, 0x71, 0x85, 0xfb, 0xb1, 0x70, 0x28, 0xdb, 0x78, 0xc7,
	0x00, 0x82, 0x3d, 0x03, 0xf8, 0x04, 0x34, 0x59, 0x46, 0x53, 0x2c, 0xbd, 0x99, 0x32, 0x22, 0x4d,
	0xb7, 0x21, 0x81, 0x31, 0x11, 0x14, 0x3e, 0x03, 0xc0, 0x4f, 0x58, 0x4e, 0x35, 0xfb, 0x50, 0xb1,
	0x4d, 0x85, 0x28, 0xfa, 0x05, 0x30, 0x04, 0x4d, 0x68, 0x16, 0xb1, 0x94, 0xe2, 0x74, 0xbd, 0xba,
	0xa6, 0xbc, 0xfc, 0xc1, 0x6e, 0x71, 0x5b, 0xc1, 0xd2, 0x50, 0x91, 0x15, 0x4d, 0x03, 0x2a, 0x7f,
	0xdc, 0x3e, 0xe3, 0x01, 0x8e, 0xd3, 0x20, 0xf6, 0x89, 0x60, 0x5c, 0xfd, 0xcc, 0x1a, 0x6e, 0xa7,
	0xe0, 0x5d, 0x45, 0x5b, 0x25, 0xfb, 0xbe, 0xde, 0x38, 0x34, 0xe0, 0xfb, 0x7a, 0xa3, 0x6d, 0x74,
	0xde, 0xd7, 0x1b, 0x8f, 0x8c, 0xa7, 0xdd, 0x97, 0xe0, 0xc8, 0xa3, 0x84, 0xfb, 0xd1, 0xbc, 0xfc,
	0x88, 0x3b, 0x1c, 0x6e, 0x77, 0x09, 0xa0, 0x56, 0xff, 0xaa, 0xbd, 0x34, 0xf8, 0x07, 0xa8, 0x2f,
	0xf8, 0x3a, 0x80, 0x3d, 0xf0, 0x60, 0x42, 0xc5, 0x76, 0x27, 0x85, 0x89, 0xdb, 0xdd, 0xdf, 0xd9,
	0x83, 0xca, 0xdf, 0x1e, 0xbe, 0x05, 0xc7, 0x13, 0x2a, 0x76, 0x76, 0x83, 0xaa, 0x59, 0x55, 0xe6,
	0xec, 0x54, 0x33, 0x7b, 0xa3, 0x70, 0x7d, 0xa0, 0x9c, 0xfe, 0xab, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x11, 0x04, 0xb0, 0xf6, 0x0b, 0x00, 0x00,
}
